# Generated by Django 4.2.5 on 2024-03-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChildrenFemale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('MiddleName', models.CharField(blank=True, max_length=100, verbose_name='Middle Name')),
                ('LastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('Profile_Picture', models.ImageField(help_text='.jpg, .png, .jpeg, .gif, .svg supported', upload_to='female_profile_pic/', verbose_name='Profile Picture')),
                ('DOB', models.DateTimeField(auto_now_add=True, verbose_name='Date of Birth')),
                ('DateJoined', models.DateTimeField(auto_now_add=True, verbose_name='User created date')),
                ('present_school', models.CharField(max_length=100, verbose_name='Name of School')),
                ('about', models.TextField(default='', max_length=1000, verbose_name='Bio Details')),
                ('address', models.TextField(default='', max_length=1000, verbose_name='Address Details')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_scholarship_beneficiary', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Female Child',
                'verbose_name_plural': 'Female Children',
            },
        ),
        migrations.CreateModel(
            name='ChildrenMale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('MiddleName', models.CharField(blank=True, max_length=100, verbose_name='Middle Name')),
                ('LastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('Profile_Picture', models.ImageField(help_text='.jpg, .png, .jpeg, .gif, .svg supported', upload_to='male_profile_pic/', verbose_name='Profile Picture')),
                ('DOB', models.DateTimeField(auto_now_add=True, verbose_name='Date of Birth')),
                ('DateJoined', models.DateTimeField(auto_now_add=True, verbose_name='User created date')),
                ('present_school', models.CharField(max_length=100, verbose_name='Name of School')),
                ('about', models.TextField(default='', max_length=1000, verbose_name='Bio Details')),
                ('address', models.TextField(default='', max_length=1000, verbose_name='Address Details')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('is_scholarship_beneficiary', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Male Child',
                'verbose_name_plural': 'Male Children',
            },
        ),
        migrations.CreateModel(
            name='Female',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('MiddleName', models.CharField(blank=True, max_length=100, verbose_name='Middle Name')),
                ('LastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('Profile_Picture', models.ImageField(help_text='.jpg, .png, .jpeg, .gif, .svg supported', upload_to='female_profile_pic/', verbose_name='Profile Picture')),
                ('DateJoined', models.DateTimeField(auto_now_add=True, verbose_name='User created date')),
                ('about', models.TextField(default='', max_length=1000, verbose_name='Bio Details')),
                ('address', models.TextField(default='', max_length=1000, verbose_name='Address Details')),
                ('teenage_status', models.IntegerField(choices=[(0, 'Not a Teenager'), (1, 'A Teenager')], default=0)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Female',
                'verbose_name_plural': 'Females',
            },
        ),
        migrations.CreateModel(
            name='Male',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100, verbose_name='First Name')),
                ('MiddleName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Middle Name')),
                ('LastName', models.CharField(max_length=100, verbose_name='Last Name')),
                ('Profile_Picture', models.ImageField(blank=True, help_text='.jpg, .png, .jpeg, .gif, .svg supported', null=True, upload_to='male_profile_pic/', verbose_name='Profile Picture')),
                ('DateJoined', models.DateTimeField(auto_now_add=True, verbose_name='Song created date')),
                ('about', models.TextField(default='', max_length=1000, verbose_name='Bio Details')),
                ('address', models.TextField(default='', max_length=1000, verbose_name='Address Details')),
                ('teenage_status', models.IntegerField(choices=[(0, 'Not a Teenager'), (1, 'A Teenager')], default=0)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Male',
                'verbose_name_plural': 'Males',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('childrenFemale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.childrenfemale')),
                ('childrenMale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.childrenmale')),
                ('female', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.female')),
                ('male', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.male')),
            ],
        ),
    ]
